apiVersion: v2
name: organizer-bot
description: A Helm chart for Discord organizer-bot
type: application
version: 0.2.0
appVersion: 0.2.7

dependencies:
- name: "redis"
  version: "15.4.1"
  repository: "https://charts.bitnami.com/bitnami"
