image:
  repository: rg.fr-par.scw.cloud/discordbots/organizer-bot
  pullPolicy: Always
  tag: "latest"

replicas: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#bot:
#  existingSecretName: organizer-bot

#redis:
#  architecture: standalone

metrics:
  prometheusRules:
    enabled: true
    rules:
      - alert: ServerSideErrors
        annotations:
          description: {{ $label.service }} has many errors on {{ $labels.command }}. Check the logs for more information.
          summary: Organizer bot has many server side errors.
        expr: sum by (command) (rate(organizer_bot_executed_commands_total{result=~"error_server"}[5m])) / sum by (command) (rate(organizer_bot_executed_commands_total{result=~"error_server|success"}[5m])) > 0.05
        for: 2m
        labels:
          severity: error

      - alert: ClientSideErrors
        annotations:
          description: {{ $label.service }} has many errors on {{ $labels.command }}. This could indicate bad UX for this command.
          summary: Organizer bot has many client side errors
        expr: sum by (command) (rate(organizer_bot_executed_commands_total{result=~"error_client"}[5m])) / sum by (command) (rate(organizer_bot_executed_commands_total{result=~"error_client|success"}[5m])) > 0.1
        for: 2m
        labels:
          severity: error
