on:
  push:
    branches:
      - "main"

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          ./hack/docker.sh build
      - name: Push image
        run: |
          ./hack/docker.sh push

  release-helm-chart:
    name: Push Helm chart
    runs-on: ubuntu-latest
    env:
      CHARTMUSEUM_AUTH_USER: ${{ secrets.CHARTMUSEUM_AUTH_USER }}
      CHARTMUSEUM_AUTH_PASS: ${{ secrets.CHARTMUSEUM_AUTH_PASS }}
      SNAPSHOT: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          ./hack/release-helm-chart.sh

  discordNotification:
    name: Send Discord notification
    runs-on: ubuntu-latest
    needs: [build-docker, release-helm-chart]
    if: failure()
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '🚨 Deployment to dev environment failed!'
      - name: Send event to Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
