on:
  push:
    tags:
      - "v*"

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Docker image tag
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build image
        run: |
          ./hack/docker.sh build
      - name: Push image
        run: |
          ./hack/docker.sh push

  #release-helm-chart:
  #  name: Push Helm chart
  #  runs-on: ubuntu-latest
  #  env:
  #    CHARTMUSEUM_AUTH_USER: ${{ secrets.CHARTMUSEUM_AUTH_USER }}
  #    CHARTMUSEUM_AUTH_PASS: ${{ secrets.CHARTMUSEUM_AUTH_PASS }}
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
  #    - run: |
  #        ./hack/release-helm-chart.sh

  deploy-bot :
    name: Deploy bot
    runs-on: ubuntu-latest
    needs: [build-docker]
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_DEFAULT_ORGANIZATION_ID: "${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}"
      SCW_K8S_CLUSTER_ID: "${{ secrets.SCW_K8S_CLUSTER_ID }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install scw
        run: |
          sudo curl -o /usr/local/bin/scw -L "https://github.com/scaleway/scaleway-cli/releases/download/v2.3.1/scw-2.3.1-linux-x86_64"
          sudo chmod +x /usr/local/bin/scw
      - name: Configure kubeconfig
        run: |
          mkdir -p "$HOME/.kube"
          scw k8s kubeconfig get "${SCW_K8S_CLUSTER_ID}" > "$HOME/.kube/config"
          chmod 400 $HOME/.kube/config
      - name: Set Docker image tag
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Deploy Helm release
        run: |
          ./hack/deploy.sh prod

  discordNotification:
    name: Send Discord notification
    runs-on: ubuntu-latest
    needs: [build-docker, deploy-bot, release-helm-chart]
    if: failure()
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '🚨 Deployment to production environment failed!'
      - name: Send event to Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
