on:
  push:
    branches:
      - "main"

jobs:
  apply-infra:
    name: Apply infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
      - name: Terraform plan
        run: |
          ./hack/infra.sh plan prod
      - name: Terraform apply
        run: |
          ./hack/infra.sh apply prod
